# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=400)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scammerlist.Catalog')),
            ],
        ),
    ]
