# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammerlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
