# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scammerlist', '0003_person_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_detail', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scammerlist.Person'),
        ),
    ]
