# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scammerlist', '0004_auto_20170424_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
