# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scammerlist', '0005_report_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_report_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 11, 47, 2, 600981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 11, 47, 2, 601439, tzinfo=utc)),
        ),
    ]
