# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scammerlist', '0006_auto_20170426_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture_url',
            field=models.CharField(default='https://assets.pcmag.com/media/images/357201-how-to-lock-down-your-facebook-profile.jpg?thumb=y&width=275&height=275', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_report_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 12, 21, 47, 474330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 12, 21, 47, 474798, tzinfo=utc)),
        ),
    ]
