# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 04:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scammerlist', '0007_auto_20170509_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_report_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 10, 4, 43, 52, 132959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 10, 4, 43, 52, 132959, tzinfo=utc)),
        ),
    ]
