# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scammerlist', '0008_auto_20170610_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='last_report_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 7, 12, 11, 0, 22, 712039, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 7, 12, 11, 0, 22, 712039, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scammerlist.Person'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
