# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scammerlist', '0009_auto_20170712_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='person',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='person',
            field=models.ManyToManyField(to='scammerlist.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_report_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 7, 12, 11, 39, 23, 242919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 7, 12, 11, 39, 23, 242919, tzinfo=utc)),
        ),
    ]
